services:
  # Ganti 'slimsapp' dengan nama layanan yang Anda inginkan di Coolify
  slimsapp:
    build: . # Ini akan menggunakan Dockerfile di root
    # Coolify akan menangani port exposure berdasarkan pengaturan FQDN.
    # Tidak perlu mendefinisikan `ports` di sini secara eksplisit kecuali untuk kasus khusus.
    volumes:
      # config/database.php akan dibuat oleh installer SLiMS dan perlu persisten
      - slims_config:/var/www/html/config
      # Data unggahan SLiMS dan data lain yang harus persisten
      - slims_files:/var/www/html/files
      - slims_images:/var/www/html/images
      - slims_repository:/var/www/html/repository
    environment:
      # Variabel ini akan diinjeksikan secara otomatis oleh Coolify ketika Anda menautkan layanan database.
      # GANTI 'mariadb_service_name_in_coolify' dengan nama aktual layanan DB Anda di Coolify.
      - DB_HOST=${{service.mariadb_service_name_in_coolify.host}}
      - DB_NAME=${{service.mariadb_service_name_in_coolify.database}}
      - DB_USER=${{service.mariadb_service_name_in_coolify.username}}
      - DB_PASSWORD=${{service.mariadb_service_name_in_coolify.password}}
      - DB_PORT=${{service.mariadb_service_name_in_coolify.port}}

      # Pengaturan PHP (juga bisa diatur di php.ini dalam Dockerfile)
      # Coolify mungkin juga memiliki cara sendiri untuk mengatur ini via UI.
      - PHP_UPLOAD_MAX_FILESIZE=64M
      - PHP_POST_MAX_SIZE=64M
      - PHP_MEMORY_LIMIT=256M
      - PHP_MAX_EXECUTION_TIME=300

      # Variabel lingkungan untuk Apache (opsional, biasanya tidak perlu diubah)
      # - APACHE_DOCUMENT_ROOT=/var/www/html

    # Coolify akan menangani health checks. Jika Anda memerlukan yang spesifik:
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost/"] # atau path SLiMS yang lebih spesifik
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 60s # Beri waktu lebih lama untuk SLiMS memulai

# Definisikan named volumes agar Coolify dapat mengelolanya
volumes:
  slims_config:
    driver: local # Default Coolify
  slims_files:
    driver: local
  slims_images:
    driver: local
  slims_repository:
    driver: local
