services:
  slimsapp:
    build: .
    restart: unless-stopped
    volumes:
      - slims_config:/var/www/html/config
      - slims_files:/var/www/html/files
      - slims_images:/var/www/html/images
      - slims_repository:/var/www/html/repository
    environment:
      # Coolify akan me-resolve {{service.mariadb.host}} dll. menjadi nilai aktual
      # dari layanan 'mariadb' yang didefinisikan di bawah.
      - DB_HOST=${{service.mariadb.host}}
      - DB_NAME=${{service.mariadb.database}} # Ini akan mengambil nilai dari MARIADB_DATABASE layanan mariadb
      - DB_USER=${{service.mariadb.username}} # Ini akan mengambil nilai dari MARIADB_USER layanan mariadb
      - DB_PASSWORD=${{service.mariadb.password}} # Ini akan mengambil nilai dari MARIADB_PASSWORD layanan mariadb
      - DB_PORT=${{service.mariadb.portInternal}} # Gunakan port internal (biasanya 3306 untuk mariadb)

      - PHP_UPLOAD_MAX_FILESIZE=64M
      - PHP_POST_MAX_SIZE=64M
      - PHP_MEMORY_LIMIT=256M
      - PHP_MAX_EXECUTION_TIME=300
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb:10.11
    restart: unless-stopped
    volumes:
      - slims_mariadb_data:/var/lib/mysql
    environment:
      # Atur nilai-nilai ini di UI Coolify untuk layanan mariadb.
      # Jika Anda tidak set di UI, nilai default di bawah akan digunakan.
      # SANGAT DISARANKAN untuk MENGGANTI nilai default ini.
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-SuperS3cretRootP@sswOrd}
      - MARIADB_DATABASE=${MARIADB_DATABASE:-slimsdatabase}
      - MARIADB_USER=${MARIADB_USER:-slimsuser}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-SuperS3cretP@sswOrd}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p${MARIADB_ROOT_PASSWORD}"]
      interval: 20s
      timeout: 10s
      retries: 5

volumes:
  slims_config:
    driver: local
  slims_files:
    driver: local
  slims_images:
    driver: local
  slims_repository:
    driver: local
  slims_mariadb_data:
    driver: local
